spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:~/FirstComeFirstServedConcurrencyTest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none